image: openjdk:11-jdk

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
    - .gradle

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - test
  - check
  - deploy

# Build
build:
  stage: build
  tags:
    - dockerex
  script: ./gradlew --build-cache assemble
  artifacts:
    paths:
      - build/libs
      - "*/build/libs"
    expire_in: 1 day

# Tests
test-except-cassandra:
  stage: test
  tags:
    - dockerex
  script: "./gradlew test --continue -x titanccp-common-cassandra:test"
  artifacts:
    reports:
      junit:
        - "build/test-results/test/TEST-*.xml"
        - "**/build/test-results/test/TEST-*.xml"
    expire_in: 28 day

# Own test for cassandra, because it requires java 8
test-cassandra:
  stage: test
  tags:
    - dockerex
  image: openjdk:8-jdk
  script: "./gradlew titanccp-common-cassandra:test"
  artifacts:
    reports:
      junit: titanccp-common-cassandra/build/test-results/test/TEST-*.xml
    expire_in: 28 days

# Checks
checkstyle:
  stage: check
  tags:
    - dockerex
  script: ./gradlew --continue checkstyle
  artifacts:
    paths:
      - build/reports/checkstyle/main.html
      - "*/build/reports/checkstyle/main.html"
    when: on_failure
    expire_in: 28 days

pmd:
  stage: check
  tags:
    - dockerex
  script: ./gradlew --continue pmd
  artifacts:
    paths:
      - build/reports/pmd/*.html
      - "*/build/reports/pmd/*.html"
    when: on_failure
    expire_in: 28 days

spotbugs:
  stage: check
  tags:
    - dockerex
  script: ./gradlew --continue spotbugs
  artifacts:
    paths:
      - build/reports/spotbugs/*.html
      - "*/build/reports/spotbugs/*.html"
    when: on_failure
    expire_in: 28 days

deploy:
  stage: deploy
  tags:
    - dockerex
  script: ./gradlew publish -PsonatypeUsername=$OSSRH_JIRA_USERNAME -PsonatypePassword=$OSSRH_JIRA_PASSWORD
  only:
    refs:
      - master
      - flink-ready
      - v0.0
    variables:
      - $OSSRH_JIRA_PASSWORD
      - $OSSRH_JIRA_USERNAME
