/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package titan.ccp.model.records;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AnomalyPowerRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5621896850840997174L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AnomalyPowerRecord\",\"namespace\":\"titan.ccp.model.records\",\"fields\":[{\"name\":\"identifier\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"*\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"*\"},{\"name\":\"valueInW\",\"type\":\"double\",\"doc\":\"*\"},{\"name\":\"anomalyScore\",\"type\":\"double\",\"doc\":\"*\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AnomalyPowerRecord> ENCODER =
      new BinaryMessageEncoder<AnomalyPowerRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AnomalyPowerRecord> DECODER =
      new BinaryMessageDecoder<AnomalyPowerRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AnomalyPowerRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AnomalyPowerRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AnomalyPowerRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AnomalyPowerRecord>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AnomalyPowerRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AnomalyPowerRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AnomalyPowerRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AnomalyPowerRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** * */
   private java.lang.String identifier;
  /** * */
   private long timestamp;
  /** * */
   private double valueInW;
  /** * */
   private double anomalyScore;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AnomalyPowerRecord() {}

  /**
   * All-args constructor.
   * @param identifier *
   * @param timestamp *
   * @param valueInW *
   * @param anomalyScore *
   */
  public AnomalyPowerRecord(java.lang.String identifier, java.lang.Long timestamp, java.lang.Double valueInW, java.lang.Double anomalyScore) {
    this.identifier = identifier;
    this.timestamp = timestamp;
    this.valueInW = valueInW;
    this.anomalyScore = anomalyScore;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return identifier;
    case 1: return timestamp;
    case 2: return valueInW;
    case 3: return anomalyScore;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: identifier = (java.lang.String)value$; break;
    case 1: timestamp = (java.lang.Long)value$; break;
    case 2: valueInW = (java.lang.Double)value$; break;
    case 3: anomalyScore = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'identifier' field.
   * @return *
   */
  public java.lang.String getIdentifier() {
    return identifier;
  }


  /**
   * Sets the value of the 'identifier' field.
   * *
   * @param value the value to set.
   */
  public void setIdentifier(java.lang.String value) {
    this.identifier = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return *
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * *
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'valueInW' field.
   * @return *
   */
  public double getValueInW() {
    return valueInW;
  }


  /**
   * Sets the value of the 'valueInW' field.
   * *
   * @param value the value to set.
   */
  public void setValueInW(double value) {
    this.valueInW = value;
  }

  /**
   * Gets the value of the 'anomalyScore' field.
   * @return *
   */
  public double getAnomalyScore() {
    return anomalyScore;
  }


  /**
   * Sets the value of the 'anomalyScore' field.
   * *
   * @param value the value to set.
   */
  public void setAnomalyScore(double value) {
    this.anomalyScore = value;
  }

  /**
   * Creates a new AnomalyPowerRecord RecordBuilder.
   * @return A new AnomalyPowerRecord RecordBuilder
   */
  public static titan.ccp.model.records.AnomalyPowerRecord.Builder newBuilder() {
    return new titan.ccp.model.records.AnomalyPowerRecord.Builder();
  }

  /**
   * Creates a new AnomalyPowerRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AnomalyPowerRecord RecordBuilder
   */
  public static titan.ccp.model.records.AnomalyPowerRecord.Builder newBuilder(titan.ccp.model.records.AnomalyPowerRecord.Builder other) {
    if (other == null) {
      return new titan.ccp.model.records.AnomalyPowerRecord.Builder();
    } else {
      return new titan.ccp.model.records.AnomalyPowerRecord.Builder(other);
    }
  }

  /**
   * Creates a new AnomalyPowerRecord RecordBuilder by copying an existing AnomalyPowerRecord instance.
   * @param other The existing instance to copy.
   * @return A new AnomalyPowerRecord RecordBuilder
   */
  public static titan.ccp.model.records.AnomalyPowerRecord.Builder newBuilder(titan.ccp.model.records.AnomalyPowerRecord other) {
    if (other == null) {
      return new titan.ccp.model.records.AnomalyPowerRecord.Builder();
    } else {
      return new titan.ccp.model.records.AnomalyPowerRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for AnomalyPowerRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AnomalyPowerRecord>
    implements org.apache.avro.data.RecordBuilder<AnomalyPowerRecord> {

    /** * */
    private java.lang.String identifier;
    /** * */
    private long timestamp;
    /** * */
    private double valueInW;
    /** * */
    private double anomalyScore;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(titan.ccp.model.records.AnomalyPowerRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.identifier)) {
        this.identifier = data().deepCopy(fields()[0].schema(), other.identifier);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.valueInW)) {
        this.valueInW = data().deepCopy(fields()[2].schema(), other.valueInW);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.anomalyScore)) {
        this.anomalyScore = data().deepCopy(fields()[3].schema(), other.anomalyScore);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing AnomalyPowerRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(titan.ccp.model.records.AnomalyPowerRecord other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.identifier)) {
        this.identifier = data().deepCopy(fields()[0].schema(), other.identifier);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.valueInW)) {
        this.valueInW = data().deepCopy(fields()[2].schema(), other.valueInW);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.anomalyScore)) {
        this.anomalyScore = data().deepCopy(fields()[3].schema(), other.anomalyScore);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'identifier' field.
      * *
      * @return The value.
      */
    public java.lang.String getIdentifier() {
      return identifier;
    }


    /**
      * Sets the value of the 'identifier' field.
      * *
      * @param value The value of 'identifier'.
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder setIdentifier(java.lang.String value) {
      validate(fields()[0], value);
      this.identifier = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'identifier' field has been set.
      * *
      * @return True if the 'identifier' field has been set, false otherwise.
      */
    public boolean hasIdentifier() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'identifier' field.
      * *
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder clearIdentifier() {
      identifier = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * *
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * *
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder setTimestamp(long value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * *
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * *
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder clearTimestamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'valueInW' field.
      * *
      * @return The value.
      */
    public double getValueInW() {
      return valueInW;
    }


    /**
      * Sets the value of the 'valueInW' field.
      * *
      * @param value The value of 'valueInW'.
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder setValueInW(double value) {
      validate(fields()[2], value);
      this.valueInW = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'valueInW' field has been set.
      * *
      * @return True if the 'valueInW' field has been set, false otherwise.
      */
    public boolean hasValueInW() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'valueInW' field.
      * *
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder clearValueInW() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'anomalyScore' field.
      * *
      * @return The value.
      */
    public double getAnomalyScore() {
      return anomalyScore;
    }


    /**
      * Sets the value of the 'anomalyScore' field.
      * *
      * @param value The value of 'anomalyScore'.
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder setAnomalyScore(double value) {
      validate(fields()[3], value);
      this.anomalyScore = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'anomalyScore' field has been set.
      * *
      * @return True if the 'anomalyScore' field has been set, false otherwise.
      */
    public boolean hasAnomalyScore() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'anomalyScore' field.
      * *
      * @return This builder.
      */
    public titan.ccp.model.records.AnomalyPowerRecord.Builder clearAnomalyScore() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AnomalyPowerRecord build() {
      try {
        AnomalyPowerRecord record = new AnomalyPowerRecord();
        record.identifier = fieldSetFlags()[0] ? this.identifier : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.Long) defaultValue(fields()[1]);
        record.valueInW = fieldSetFlags()[2] ? this.valueInW : (java.lang.Double) defaultValue(fields()[2]);
        record.anomalyScore = fieldSetFlags()[3] ? this.anomalyScore : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AnomalyPowerRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<AnomalyPowerRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AnomalyPowerRecord>
    READER$ = (org.apache.avro.io.DatumReader<AnomalyPowerRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.identifier);

    out.writeLong(this.timestamp);

    out.writeDouble(this.valueInW);

    out.writeDouble(this.anomalyScore);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.identifier = in.readString();

      this.timestamp = in.readLong();

      this.valueInW = in.readDouble();

      this.anomalyScore = in.readDouble();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.identifier = in.readString();
          break;

        case 1:
          this.timestamp = in.readLong();
          break;

        case 2:
          this.valueInW = in.readDouble();
          break;

        case 3:
          this.anomalyScore = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










